### ISSUE TITLE
Width truncation broke lipgloss border rendering

### ISSUE THREAD

**Issue by shaunco** [charmbracelet/x#123]
**Describe the bug**
The https://github.com/charmbracelet/x/commit/30996771cb6ac2ffd8069f2cb516a6a9b115e739 or https://github.com/charmbracelet/x/commit/fe8416275fa6a252117fda3f3957eb9b30ce1159 change seems to have made full dimension rendering of lipgloss border box content produce wider than allowed lines, which causes 1 character to wrap onto the next line for each line, which breaks up the border and content with new empty lines between each row.

```go
	viewBox = lipgloss.NewStyle().
			Border(lipgloss.RoundedBorder()).
			BorderForeground(green).
			Padding(1).
			Margin(1)

	width := consoleWidth - viewBox.GetHorizontalFrameSize()
	height := consoleHeight - viewBox.GetVerticalFrameSize()
	return viewBox.
		Height(height).
		MaxHeight(consoleHeight).
		Width(width).
		MaxWidth(consoleWidth).
		Margin(0).
		Render("test content")
```

With lipgloss 0.11.0, which pulled in x/ansi v0.1.2, this works great and draws a nice border around everything. When lipgloss 0.12.0 moved to x/ansi v0.1.3, this broke and started outputting wider than allowed lines, which causes unexpected wrap, which causes blank lines between each row. The issue persists if I go back to lipgloss 0.11.0, but still using x/ansi 0.1.3. The issue goes away if I go back to x/ansi 0.1.2.

**Comment by luevano** [comment]
Already reported it too on #122 , I guess my title name is not searchable. I'll update my title as well.
