### ISSUE TITLE
ansi: inconsistent handling of tabs

### ISSUE THREAD

**Issue by pachecot** [charmbracelet/x#237]
`ansi.StringWidth` treats tabs as zero width, but `ansi.Harwrap` treats tabs a non-zero width of 1.

one would get would unexpected results with a construct such as this :
```go
	s := "foo\tbar"
	n := ansi.StringWidth(s)           // n == 6
	p := ansi.Hardwrap(s, n, true)

	// p == "foo\tba\nr"   
	// not  "foo\tbar" as one might expect 
```

not sure if this is a bug or intended behavior. 

one of the tests for Hardwrap is..
```
	{"tab", "foo\tbar", 3, "foo\n\tba\nr", true},
```

**Comment by aymanbagabas** [comment]
Thank you, @pachecot, for opening this issue. I've opened https://github.com/charmbracelet/x/pull/238 to patch this one 🙂
