### ISSUE TITLE
Refactor or add a method similar to WaitFinished that returns an error

### ISSUE THREAD

**Issue by polds** [charmbracelet/x#65]
**Is your feature request related to a problem? Please describe.**
I would like to author a test where I expect [WaitFinished](https://github.com/charmbracelet/x/blob/main/exp/teatest/teatest.go#L198-L203) to timeout / fail. However, the behavior is to `tb.Fatal` under the hood, even though I expect this case.

Edit: The main usecase is in checking that the program did not quit by a user sending specific keystrokes. 

**Describe the solution you'd like**
Potentially introduce a new method that can return an error so backwards compatibility isn't introduced to the `WaitFinished` method. Then refactor `waitDone` to return [this line](https://github.com/charmbracelet/x/blob/main/exp/teatest/teatest.go#L173) as an error instead of triggering a Fatal on the test.

**Describe alternatives you've considered**
I was alternatively hoping that calling [Quit](https://github.com/charmbracelet/x/blob/main/exp/teatest/teatest.go#L237-L241) multiple times would return an error if it had already been called. If that method did return a real error after shutdown I could use that and check whether I expected a nil error, something like:

```go
if tc.expectedShutdown {
  m.WaitFinished(t, teatest.WithFinalTimeout(time.Millisecond))
}

// We hope Quit will fail now because the program has exited.
if err := m.Quit(); err == nil && tc.expectedShutdown {
    t.Error("Quit() got nil error indicating no program shutdown, expected program to have terminated")
}
```

However:

```go
t.Log(m.Quit()) // nil
t.Log(m.Quit()) // nil
t.Log(m.Quit()) // nil
```

The error is always nil.

**Comment by caarlos0** [comment]
hey!

would #74 suffice?
